name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js specific version
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: install
        run: |
          ./ci/install.sh

      - name: test
        run: |
          npm run build
          npm test
